# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: testing1

stages:
- stage: terraforminit
  jobs:
  - job: initialise
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest' 
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'rgpipeline'
        backendAzureRmStorageAccountName: 'firstyamlstorage'
        backendAzureRmContainerName: 'pipelinecontainer'
        backendAzureRmKey: 'remote.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'rgpipeline'





